# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=70)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('is_new', models.BooleanField(default=False)),
            ],
        ),
    ]
